#!/bin/sh

#+------------------------------------------------------------------------------+
#|                     Lightshot print screen Linux handler                     |
#|                         Language: POSIX shell script                         |
#|                     Copyright: 2018-2021 Vlastimil Burian                    |
#|                      M@il: info[..]vlastimilburian[..]cz                     |
#|                               License: GPL 3.0                               |
#|                             Version: 6.0 (final)                             |
#|                         GitHub: https://git.io/fx2US                         |
#+------------------------------------------------------------------------------+

# global shell script variable(s)

# the hotkey variable for easy set-up; overridable with -k switch,
# run this script with -h for complete help to this script; just run it to test out
# set this to the same hotkey which you have set up in your Lightshot options
# for the left control key and the print screen key put in Control_L+Print
hotkey='Print'

# global shell script option(s)

# treat unset variables as an error when substituting
# clarification: this means that accessing any unassigned variable
# produces immediate termination of the script with an error produced
set -o nounset

tput_setup_nix ()
# Linux `tput` uses terminfo
{
    tput_cmd_set_fg_color='tput setaf'
    tput_number_of_colors=$(tput colors 2> /dev/null) &&
    tput_bold=$(tput bold 2> /dev/null) &&
    tput_reset=$(tput sgr0 2> /dev/null)
}

tput_setup_bsd ()
# BSD `tput` uses termcap
{
    tput_cmd_set_fg_color='tput AF'
    tput_number_of_colors=$(tput Co 2> /dev/null) &&
    tput_bold=$(tput md 2> /dev/null) &&
    tput_reset=$(tput me 2> /dev/null)
}

tput_setup_none ()
# no unset variables allowed due to `set -u`
{
    tput_cmd_set_fg_color=
    tput_number_of_colors=
    tput_bold=
    tput_reset=
}

# this routine prepares `tput` on Linux and BSD
tput_setup_none

if command -v tput > /dev/null 2>&1; then

    if tput setaf > /dev/null 2>&1; then

        tput_setup_nix || tput_setup_none

    elif tput AF > /dev/null 2>&1; then

        tput_setup_bsd || tput_setup_none

    fi

fi

# shellcheck disable=SC2120
is_script_running_interactively ()
# function to determine if stdin is connected (running interactively)
{
    if [ "$#" -ne 0 ]; then
        printf >&2 '%s\n' \
            "is_script_running_interactively() input check" \
            "Some argument(s) was/were passed to the function!" \
            "No argument expected. Passed: $#: $*"
        exit 1
    fi
    # test if file descriptor 0 = standard input is connected to the terminal
    [ -t 0 ]
}

is_terminal_tput_capable ()
# function to test `tput` availability and capability
{
    # shellcheck disable=SC2119
    [ -n "$tput_cmd_set_fg_color" ] && [ -n "$tput_number_of_colors" ] && [ -n "$tput_bold" ] && [ -n "$tput_reset" ] &&
    is_script_running_interactively && [ "$tput_number_of_colors" -ge 8 ] &&
    { $tput_cmd_set_fg_color 1 && printf '%s\n' "${tput_bold}TEST$tput_reset"; } > /dev/null 2>&1
}

if is_terminal_tput_capable; then
    # setup of the most basic color set
    color_red=$tput_bold$($tput_cmd_set_fg_color 1)
    color_green=$tput_bold$($tput_cmd_set_fg_color 2)
    color_yellow=$tput_bold$($tput_cmd_set_fg_color 3)
    color_blue=$tput_bold$($tput_cmd_set_fg_color 4)
    color_magenta=$tput_bold$($tput_cmd_set_fg_color 5)
    color_cyan=$tput_bold$($tput_cmd_set_fg_color 6)
    color_white=$tput_bold$($tput_cmd_set_fg_color 7)
else
    # no unset variables allowed, due to `set -u`
    color_red=
    color_green=
    color_yellow=
    color_blue=
    color_magenta=
    # shellcheck disable=SC2034
    color_cyan=
    color_white=
fi

is_integer ()
# function to test one variable for integer, generic
{
    if [ "$#" -ne 1 ]; then
        printf >&2 '%s\n' \
            "is_integer() input check" \
            "Single argument was not passed to the function!" \
            "One variable to test expected. Passed: $#: $*"
        exit 1
    fi
    case "${1#[+-]}" in
        (*[!0123456789]*) return 1 ;;
        ('')              return 1 ;;
        (*)               return 0 ;;
    esac
}

is_unsigned_integer ()
# function using is_integer(), but only unsigned integers pass it
{
    if [ "$#" -ne 1 ]; then
        printf >&2 '%s\n' \
            "is_unsigned_integer() input check" \
            "Single argument was not passed to the function!" \
            "One variable to test expected. Passed: $#: $*"
        exit 1
    fi
    case "$1" in
        ([+-]*) return 1 ;;
    esac
    is_integer "$1"
}

is_valid_exit_code ()
# function using is_unsigned_integer(), but limiting the valid input
# to unsigned integer in a range <0;125> which is "safe",
# the remaining range is reserved or otherwise not recommended
{
    if [ "$#" -ne 1 ]; then
        printf >&2 '%s\n' \
            "is_valid_exit_code() input check" \
            "Single argument was not passed to the function!" \
            "One variable to test expected. Passed: $#: $*"
        exit 1
    fi
    is_unsigned_integer "$1" && [ "$1" -le 125 ]
}

dump_args ()
# function to detect basic variable types passed to my functions:
# empty, integer, file (specific info), the rest is considered string
{
    # we do not write anything for 0 arguments
    [ "$#" -eq 0 ] && return 1

    i=1
    printf '%s\n' \
        "${color_yellow}dump_args()$tput_reset" \
        "$color_white$# arguments inspected:$tput_reset"
    while [ "$#" -gt 0 ]; do
        printf "[$color_white%d$tput_reset]: '%s' " "$i" "$1"
        if [ -z "$1" ]; then
            printf '%s' "(${color_blue}empty$tput_reset)"
        elif is_integer "$1"; then
            printf '%s' "(${color_green}integer$tput_reset)"
        elif [ -e "$1" ]; then
            printf '%s' "(${color_magenta}file: $(file -b "$1")$tput_reset)"
        else
            printf '%s' "(${color_red}string$tput_reset)"
        fi
        printf '\n'
        shift
        i=$(( i + 1 ))
    done
} >&2

print_error ()
# function to print error messages
{
    if ! { [ "$#" -eq 2 ] && [ -n "$1" ] && [ -n "$2" ]; } then
        dump_args "$@"
        # shellcheck disable=SC2016
        printf '%s\n' \
            'print_error() input check' \
            'Wrong number, type or empty arguments have been passed to the function.' \
            'Expected the following strings: $1 = error heading, $2 = error message.'
        exit 1
    fi
    printf '%s\n' \
        "Error heading: $1" \
        "Error message: $2"

} >&2

print_error_and_exit ()
# function to print error messages and exit right away
{
    if ! { [ "$#" -eq 2 ] && [ -n "$1" ] && [ -n "$2" ]; } &&
       ! { [ "$#" -eq 3 ] && [ -n "$1" ] && [ -n "$2" ] && is_valid_exit_code "$3" && [ "$3" -ge 1 ]; } then
        dump_args "$@"
        # shellcheck disable=SC2016
        printf '%s\n' \
            'print_error_and_exit() input check' \
            'Wrong number, type or empty arguments have been passed to the function.' \
            'Expected the following strings: $1 = error heading, $2 = error message.' \
            'Optionally, accepting a number: $3 = exit code; if not given 1 is used.' \
            'Acceptable exit code range: anywhere between <1;125>; 1 is the default.'
        exit 1
    fi
    print_error "$1" "$2"
    exit "${3:-1}"
} >&2

# shellcheck disable=SC2120
is_user_root ()
{
    if [ "$#" -ne 0 ]; then
        dump_args "$@"
        print_error_and_exit 'is_user_root() input check' 'Some arguments have been passed to the function! No arguments expected.'
    fi
    [ "$(id -u)" -eq 0 ]
}

# shellcheck disable=SC2119
if is_user_root; then
    print_error_and_exit 'is_user_root()' 'Running this script with root privileges is not recommended! Expected normal user.'
fi

check_requirements ()
{
    if [ "$#" -eq 0 ]; then
        print_error_and_exit 'check_requirements() input check' 'No arguments passed to the function! At least one program/package name pair expected.'
    fi
    if [ "$(( $# % 2 ))" -ne 0 ]; then
        dump_args "$@"
        print_error_and_exit 'check_requirements() input check' 'Odd number of arguments has been passed to the function. Program and package names in pairs expected.'
    fi

    dependency_missing=false

    while [ "$#" -gt 0 ]; do
        if ! command -v "$1" > /dev/null 2>&1; then
            dependency_missing=true
            print_error 'check_requirements(): required dependency' "This script requires '$1' program but it is not available on this system! On a usual OS, please install '$2' package."
        fi
        shift 2
    done

    if "$dependency_missing"; then
        exit 1
    fi
}

check_requirements \
    'pgrep'      'procps' \
    'xdotool'    'xdotool'

print_usage_and_exit ()
{
    if ! { [ "$#" -eq 1 ] && is_valid_exit_code "$1"; } then
        dump_args "$@"
        # shellcheck disable=SC2016
        print_error_and_exit 'print_usage_and_exit() input check' 'Number required: $1 = exit code from the script.'
    fi
    [ "$1" -ne 0 ] && exec >&2
cat << EOF
Script  : Lightshot print screen Linux handler
Version : 6.0 (final)
GitHub  : https://git.io/fx2US
--------------------------------------------------------------------
Description: This script works with XDOTOOL to trigger Print Screen
key combination in Lightshot application installed on Linux in Wine.
License: GPL 3.0. The code itself can be further enhanced by others.
The script, however, won't launch Lightshot for you due to variable
installation locations which make it impossible. You need to run it!
--------------------------------------------------------------------
Usage in terminal: ./$(basename "$0") [-k "HotKey"]

    -k 'HotKey': Optional switch requiring one argument,
        which is the print screen hotkey combination.
        For the left Control key and the Print Screen key
        that would be 'Control_L+Print' (as an example).

    -h: Show this help.

Usage in desktop environment:

    You need to find Keyboard shortcuts, and re-map Print to run
    this script, an example from Linux Mint is placed on GitHub.
EOF
    exit "$1"
}

while getopts ":hk:" cli_option; do
    case "$cli_option" in
        (k) hotkey=$OPTARG        ; break ;;
        (h) print_usage_and_exit 0; break ;;
        (*) print_usage_and_exit 1; break ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ "$#" -ne 0 ]; then
    dump_args "$@"
    print_usage_and_exit 1
fi

get_process_id ()
{
    if ! { [ "$#" -eq 1 ] && [ -n "$1" ]; } then
        dump_args "$@"
        # shellcheck disable=SC2016
        print_error_and_exit 'get_process_id() input check' 'String required: $1 = a process name to find id to.'
    fi
    # -o, --oldest: select least recently started
    pgrep -o "$1"
}

get_window_id ()
{
    if ! { [ "$#" -eq 2 ] && is_unsigned_integer "$1" && [ -n "$2" ]; } then
        dump_args "$@"
        print_error_and_exit 'get_window_id() input check' "Two valid arguments were not passed to the function! Expected a process id (unsigned integer) and a window name (string)."
    fi
    #--all  : Require all conditions to be met.
    #--limit: Stop searching after finding N matching windows.
    #--pid  : Match windows that belong to a specific process id.
    #--name : Match against the window name. This is the same string that is displayed in the window titlebar.
    if ! xdotool search --all --limit 1 --pid "$1" --name "$2"; then
        print_error_and_exit 'get_window_id()' "No window matching process id '$1' and window name '$2' has been found."
    fi
}

lightshot_process_id=$(get_process_id Lightshot.exe)

if ! is_unsigned_integer "$lightshot_process_id"; then
    # shellcheck disable=SC2016
    print_error_and_exit 'is_unsigned_integer $lightshot_process_id' "Lightshot process is not running. Launch Lightshot app first, please."
fi

lightshot_window_id=$(get_window_id "$lightshot_process_id" Lightshot)

if ! is_unsigned_integer "$lightshot_window_id"; then
    # shellcheck disable=SC2016
    print_error_and_exit 'is_unsigned_integer $lightshot_window_id' 'Lightshot process was found (is running) but its window was not found for some reason / get_window_id() returned an empty value.'
fi

if xdotool key --window "$lightshot_window_id" "$hotkey"; then
    printf '%s\n' \
        "Success, the hotkey = $hotkey was successfully sent to Lightshot window!" \
        'However, if Lightshot overlay did not appear, you probably sent a bad hotkey.' \
        'In such a case, please adjust the hotkey in Lightshot tray options menu.'
else
    print_error_and_exit "xdotool key --window $lightshot_window_id $hotkey" 'The send-hotkey command encountered an error.'
fi
